<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Person;
use Doctrine\ORM\EntityRepository;
use function Doctrine\ORM\QueryBuilder;

/**
 * MovieRepository
 **
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends EntityRepository
{
    public function getMoviesOf(Person $person)
    {
        $qb = $this->createQueryBuilder('m');

        $qb
            ->join('m.people', 'p')
            ->where($qb->expr()->eq('p.person', ':person'))
            ->setParameter('person', $person->getId())
        ;

        return $qb->getQuery()->getResult();

    }
}
