<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Person;
use function Doctrine\ORM\QueryBuilder;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMoviesOf(Person $person)
    {
        $qb = $this->createQueryBuilder('m');

        $qb
            ->join('m.person', 'p')
            ->where($qb->expr()->eq('p.id', ':person'))
            ->setParameter('person', $person->getId())
        ;

        return $qb->getQuery()->getResult();
    }
}
