<?php

namespace AppBundle\Repository;

/**
 * MovieHasPeopleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieHasPeopleRepository extends \Doctrine\ORM\EntityRepository
{
}
