<?php

namespace AppBundle\Repository;

/**
 * ShowingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShowingRepository extends \Doctrine\ORM\EntityRepository
{
}
